"""add item, inventory, shop inventory tables

Revision ID: 36248c8b4f28
Revises: 48edb14848b1
Create Date: 2026-05-05 12:24:54.312971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36248c8b4f28'
down_revision = '48edb14848b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('next_level_xp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quests_completed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('last_bonus_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_bonus_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('quests_completed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('next_level_xp',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
